cookies_demo/cookies_app/urls.py
from django.urls import path
from . import views

app_name = 'cookies_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('blowup/', views.blowup, name='blowup'),
    path('impossible/', views.impossible, name='impossible'),
]

cookies_demo/cookies_demo/urls.py
# from cookies_demo.cookies_app.views import handler400
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cookies_app.urls')),
]

handler400 = 'cookies_app.views.handler400'
handler500 = 'cookies_app.views.handler500'
handler403 = 'cookies_app.views.handler403'
handler404 = 'cookies_app.views.handler404'

cookies_demo/cookies_app/models.py
from django.db import models
from django.contrib.auth.models import User


# class UserProfile(models.Model):
#     login_name = models.OneToOneField(
#         User, on_delete=models.CASCADE, related_name='profile_ref')

#     def __str__(self):
#         return self.login_name.last_name + ', ' + self.login_name.first_name

cookies_demo/cookies_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.contrib.auth.models import User
import requests
import django.contrib.auth
from datetime import datetime
from django.contrib.auth.decorators import user_passes_test
# Utility functions to get and translate date objects, the worst kind of objects..


# impossible skill check
def impossible_check(user):
    return (user or False)


# Regular view functions

def home(request):
    if request.user.is_authenticated:
        dt = datetime.now()
        context= {
            'message': 'Hello World',
            'setting_cookie': False,
            'year': dt.year,
            'month': dt.month,
            'day': dt.day,
            'hour': dt.hour,
            'minute': dt.minute,
            'second': dt.second,
            'username': request.user.username,
        }
        context['setting_cookie'] = True
        return render(request, 'cookies_app/home.html', context)
    else:
        return HttpResponseRedirect(reverse('cookies_app:login'))

def login(request):
    # print(request.POST)
    # print(request.GET)
    if request.method == 'POST':
        secret_key = settings.RECAPTCHA_SECRET_KEY
        data = {
            'response': request.POST['g-recaptcha-response'],
            'secret': secret_key,
        }
        resp = requests.post(
            'https://www.google.com/recaptcha/api/siteverify', data=data)
        result_json = resp.json()
        # print(result_json)
        ################################################
        if not result_json['success'] or result_json['score'] <= 0.5:
            context = {
                'site_key': settings.RECAPTCHA_SITE_KEY
            }
            return render(request, 'cookies_app/login.html', context)
        ################################################
        # user login logic here
        username = request.POST['username']
        password = request.POST['password']
        user = django.contrib.auth.authenticate(
            request, username=username, password=password)
        next = request.GET.get('next', reverse('cookies_app:home'))
        return HttpResponseRedirect(next)
    context = {
        'site_key': settings.RECAPTCHA_SITE_KEY
    }
    if request.method == 'POST' and not result_json.get('success'):
        context['is_robot'] = True
    return render(request, 'cookies_app/login.html', context)

def register(request):
    # print('GET' + str(request.GET))
    if request.method == 'POST':
        django.contrib.auth.logout(request)
        # print(request.POST)
        secret_key = settings.RECAPTCHA_SECRET_KEY
        data = {
            'response': request.POST['g-recaptcha-response'],
            'secret': secret_key,
        }
        resp = requests.post(
            'https://www.google.com/recaptcha/api/siteverify', data=data)
        result_json = resp.json()
        # print(result_json)
        # create user logic here
        if not result_json['success'] or result_json['score'] <= 0.5:
            context = {
                'site_key': settings.RECAPTCHA_SITE_KEY
            }
            return render(request, 'cookies_app/register.html', context)
        password = request.POST['password']
        password_v = request.POST['password_v']
        if password != password_v:
            context = {
                'site_key': settings.RECAPTCHA_SITE_KEY
            }
            return render(request, 'cookies_app/register.html', context)
        username = request.POST['username']
        if User.objects.filter(username=username).exists():
            user = django.contrib.auth.authenticate(
                request, username=username, password=password)
            if user is None:
                return HttpResponseRedirect(reverse('cookies_app:login'))
            django.contrib.auth.login(request, user)
            return HttpResponseRedirect(reverse('cookies_app:profile'))
        user = User.objects.create_user(
            username, request.POST['email'], password)
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.save()
        django.contrib.auth.login(request, user)
        return HttpResponseRedirect(reverse('cookies_app:home'))
    context = {
        'site_key': settings.RECAPTCHA_SITE_KEY,
    }
    return render(request, 'cookies_app/register.html', context)

def logout(request):
    django.contrib.auth.logout(request)
    return HttpResponseRedirect(reverse('cookies_app:login'))

def handler404(request, exception):
    context = {
        'code': '404',
        'message': 'Not found. Where\'s the Marauder\'s Map when you need it?'
    }
    return render(request, 'cookies_app/handler.html', context)

def handler500(request):
    context = {
        'code': '500',
        'message': 'Server error. This one isn\'t your fault.'
    }
    return render(request, 'cookies_app/handler.html', context)

def handler403(request, exception):
    context = {
        'code': '403',
        'message': 'Forbidden. You. Shall not. Pass.'
    }
    return render(request, 'cookies_app/handler.html', context)

def handler400(request, exception):
    context = {
        'code': '400',
        'message': 'Bad Request. Perhaps you could ask more politely?'
    }
    return render(request, 'cookies_app/handler.html', context)

def blowup(request):
    output = User.objects.filter('Bogus Data')
    return HttpResponse(output)

@user_passes_test(impossible_check)
def impossible(request):
    return HttpResponseRedirect(reverse('cookies_app:login'))

cookies_demo/cookies_app/templates/cookies_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <style>
        body {
            background-color: ivory;
        }
    </style>
    {% block style %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'cookies_app:logout' %}">Logout</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'cookies_app:login' %}">Login</a></li>
                {% endif %}
                <li class="nav-item"><a href="http://localhost:8000/madeup" class="nav-link">Bad URL request on server</a></li>
                <li class="nav-item"><a href="{% url 'cookies_app:blowup' %}" class="nav-link">Make the server blow up</a></li>
                <li class="nav-item"><a href="{% url 'cookies_app:impossible' %}" class="nav-link">Impossible permission check</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    {% block javascript %}
    {% endblock %}
</body>

</html>

cookies_demo/cookies_app/templates/cookies_app/handler.html
{% extends 'cookies_app/base.html' %}
{% block title %}Error {{code}}{% endblock %}
{% block style %}
{% endblock %}
{% block body %}
<div class="container">
    <p><h1>Error {{code}}</h1></p>
    <p><h2>{{message}}</h2></p>

</div>
{% endblock %}
{% block javascript %}

{% endblock %}

cookies_demo/cookies_app/templates/cookies_app/home.html
{% extends 'cookies_app/base.html' %}
{% block title %}Home{% endblock %}
{% block style %}
<style>

</style>
{% endblock %}
{% block body %}

{% endblock %}
{% block javascript %}
<script>
    const TIMEDELTA = 10000

    ////////////////////////////////////////////////////////
    //           Cookie Functions
    ///////////////////////////////////////////////////////

    const getItem = key =>
        document.cookie.split("; ").reduce((total, currentCookie) => {
            const item = currentCookie.split("=")
            const storedKey = item[0]
            const storedValue = item[1]
            console.log('FOUND COOKIE')
            console.log(storedKey)
            console.log(storedValue)

            return key === storedKey ? decodeURIComponent(storedValue) : total
        }, "")

    const setItem = (key, value, date_time_from_server) => {
        const now = new Date()

        // set the time to be now + numberOfDays
        now.setTime(date_time_from_server.getTime() + TIMEDELTA)

        document.cookie = `${key}=${value}; expires=${now.toUTCString()}; path=/`;
    }

    /**
     *
     * @param {String} key The key to store our data to
     * @param {String} defaultValue The default value to return in case the cookie doesn't exist
     */
    const useCookie = (key, defaultValue) => {
        const getCookie = () => getItem(key) || defaultValue
        let cookie = getCookie()
        // console.log('Cookie is ' + cookie)

        // const updateCookie = (value, numberOfDays) => {
        //     setCookie(value)
        //     setItem(key, value, numberOfDays)
        // }

        return cookie
    }


    ///////////////////////////////////////////////
    //      Page load script
    ///////////////////////////////////////////////

    const year = '{{year}}'
    const month = '{{month}}'
    const day = '{{day}}'
    const hour = '{{hour}}'
    const minute = '{{minute}}'
    const second = '{{second}}'
    const constructedDate = new Date(`${year}-${month}-${day} ${hour}:${minute}:${second}`)
    console.log(constructedDate)
    // const cookie = useCookie('cookie_demo', null)

    setItem('cookie_demo', '{{username}}', constructedDate)
    const interval = setInterval(() => {
        let tempDate = new Date()
        console.log(tempDate - constructedDate)
        let tempString = getItem('cookie_demo')
        console.log('/////////////////////////////')
        console.log(tempString)
    }, 3000)

</script>
{% endblock %}

cookies_demo/cookies_app/templates/cookies_app/login.html
{% extends 'cookies_app/base.html' %}
{% block title %}Login{% endblock %}
{% block style %}

{% endblock %}
{% block body %}
<div class="container" id="div_body">
    <h3>User Login</h3>
    <form id="form_input" action="" method="POST">
        {% csrf_token %}
        <input type="text" placeholder="username" name="username" required>
        <input type="password" placeholder="password" name="password" required>
        <input type="hidden" id="recaptcha" name="g-recaptcha-response">
        <!-- <button class="btn btn-primary g-recaptcha" data-sitekey="6LdLbdQZAAAAAFPUDUmXHIDFo7tjwHyUDb40W-lG"
            data-callback="onSubmit" data-action="submit" type="submit">Login</button> -->
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    <a href="{% url 'cookies_app:register' %}">
        <h5>Not Registered? Click here to create an account!</h5>
    </a>
</div>
{% endblock %}
{% block javascript %}
<script src="https://www.google.com/recaptcha/api.js?render={{site_key}}"></script>
<script>
    // function onSubmit(token) {
    //     document.getElementById("form").submit();
    // }
    grecaptcha.ready(function () {
        // 4
        $('#form_input').submit(function (e) {
            let form = this;
            // 5
            e.preventDefault()
            grecaptcha.execute('{{ site_key }}', { action: 'form' }).then(function (token) {
                console.log(token)
                // 6
                $('#recaptcha').val(token)
                // 7
                form.submit()
            });
        })
    });
</script>
{% endblock %}

cookies_demo/cookies_app/templates/cookies_app/register.html
{% extends 'cookies_app/base.html' %}
{% block title %}Registration{% endblock %}
{% block style %}

{% endblock %}
{% block body %}
<div class="container" id="div_body">
    <h3>User Registration</h3>
    <form id="form_input" action="{% url 'cookies_app:register' %}" method="POST">
        {% csrf_token %}
        <input type="text" placeholder="username" name="username" required>
        <input type="text" placeholder="first name" name="first_name" required>
        <input type="text" placeholder="last name" name=last_name required>
        <input type="email" placeholder="email address" name="email" required>
        <input type="password" placeholder="password" oninput="password_check()" name="password" id="password" required>
        <input type="password" placeholder="password" oninput="password_check()" name="password_v" id="password_v"
            required>
        <input type="hidden" id="recaptcha" name="g-recaptcha-response">
        <button class="btn btn-primary" type="submit" id="submit_btn">Submit</button>
    </form>
</div>
{% endblock %}
{% block javascript %}
<script src="https://www.google.com/recaptcha/api.js?render={{site_key}}"></script>
<script>
    function password_check() {
        if ($('#password').val() != $('#password_v').val()) {
            $('#submit_btn').addClass('disabled')
            console.log('Passwords don\'t match.')
        }
        else {
            $('#submit_btn').removeClass('disabled')
            console.log('Passwords match.')
        }
    }
    grecaptcha.ready(function () {
        // 4
        $('#form_input').submit(function (e) {
            let form = this;
            // 5
            e.preventDefault()
            grecaptcha.execute('{{ site_key }}', { action: 'form' }).then(function (token) {
                console.log(token)
                // 6
                $('#recaptcha').val(token)
                // 7
                form.submit()
            });
        })
    });
</script>
{% endblock %}